# Generated by Django 3.2.7 on 2021-09-17 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='followers',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
