# Generated by Django 3.2.7 on 2021-09-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_userprofile_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='time',
            field=models.TimeField(default='11:11'),
        ),
    ]
