# Generated by Django 3.2.7 on 2021-09-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_repository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='key',
        ),
    ]
